

CREATE PROCEDURE "SA"."p_DeleteEMPLOYEE"
/***********************************************************
* Code generated by SoftTree SQL Assistant © v6.2.99
*
* Procedure description: This procedure is used for 
*                        deleting records from table 
*                        EMPLOYEE
* Date:   5/29/2012 
* Author: SA
*
* Changes
* Date        Modified By            Comments
************************************************************
* 5/29/2012 SA Initial version
************************************************************/
(
    a_EMPNO CHARACTER(6)
)
LANGUAGE SQL
MODIFIES SQL DATA
BEGIN
    DELETE FROM "SA"."EMPLOYEE"
    WHERE  EMPNO = a_EMPNO ;
END
$$$


-- uncomment the following line if you want to grant procedure permissions to some other user or role
-- GRANT EXECUTE ON "SA"."p_DeleteEMPLOYEE" TO "some user or role here" ;



$$$



CREATE PROCEDURE "SA"."p_GetEMPLOYEE"
/***********************************************************
* Code generated by SoftTree SQL Assistant © v6.2.99
*
* Procedure description: This procedure is used for 
*                        retrieving records from table 
*                        EMPLOYEE
* Date:   5/29/2012 
* Author: SA
*
* Changes
* Date        Modified By            Comments
************************************************************
* 5/29/2012 SA Initial version
************************************************************/
(
    a_EMPNO CHARACTER(6)
)
RESULT SETS 1
LANGUAGE SQL
READS SQL DATA
BEGIN
    DECLARE c CURSOR FOR
      SELECT EMPNO 
      FROM "SA"."EMPLOYEE"
      WHERE  EMPNO = a_EMPNO ;

    OPEN c;
END
$$$

-- uncomment the following line if you want to grant procedure permissions to some other user or role
-- GRANT EXECUTE ON "SA"."p_GetEMPLOYEE" TO "some user or role here" ;


$$$



CREATE PROCEDURE "SA"."p_SaveEMPLOYEE"
/***********************************************************
* Code generated by SoftTree SQL Assistant © v6.2.99
*
* Procedure description: This procedure is used for adding 
*                        and updating records in table 
*                        EMPLOYEE
* Date:   5/29/2012 
* Author: SA
*
* Changes
* Date        Modified By            Comments
************************************************************
* 5/29/2012 SA Initial version
************************************************************/
(
    a_EMPNO CHARACTER(6),
    a_FIRSTNME VARCHAR(12),
    a_MIDINIT CHARACTER(1),
    a_LASTNAME VARCHAR(15),
    a_WORKDEPT CHARACTER(3),
    a_PHONENO CHARACTER(4),
    a_HIREDATE DATE,
    a_JOB CHARACTER(8),
    a_EDLEVEL SMALLINT,
    a_SEX CHARACTER(1),
    a_BIRTHDATE DATE,
    a_SALARY DECIMAL,
    a_BONUS DECIMAL,
    a_COMM DECIMAL
)
LANGUAGE SQL
MODIFIES SQL DATA
BEGIN
    IF EXISTS 
    (    
         SELECT * 
         FROM "SA"."EMPLOYEE"
         WHERE  EMPNO = a_EMPNO
    )
    THEN 
         INSERT INTO "SA"."EMPLOYEE"
         (
             EMPNO,
             FIRSTNME,
             MIDINIT,
             LASTNAME,
             WORKDEPT,
             PHONENO,
             HIREDATE,
             JOB,
             EDLEVEL,
             SEX,
             BIRTHDATE,
             SALARY,
             BONUS,
             COMM
         )
         VALUES 
         (
             a_EMPNO,
             a_FIRSTNME,
             a_MIDINIT,
             a_LASTNAME,
             a_WORKDEPT,
             a_PHONENO,
             a_HIREDATE,
             a_JOB,
             a_EDLEVEL,
             a_SEX,
             a_BIRTHDATE,
             a_SALARY,
             a_BONUS,
             a_COMM
         ) ;
    ELSE
         UPDATE "SA"."EMPLOYEE"
         SET EMPNO = a_EMPNO,
             FIRSTNME = a_FIRSTNME,
             MIDINIT = a_MIDINIT,
             LASTNAME = a_LASTNAME,
             WORKDEPT = a_WORKDEPT,
             PHONENO = a_PHONENO,
             HIREDATE = a_HIREDATE,
             JOB = a_JOB,
             EDLEVEL = a_EDLEVEL,
             SEX = a_SEX,
             BIRTHDATE = a_BIRTHDATE,
             SALARY = a_SALARY,
             BONUS = a_BONUS,
             COMM = a_COMM
         WHERE  EMPNO = a_EMPNO ;
    END IF;
END
$$$

-- uncomment the following line if you want to grant procedure permissions to some other user or role
-- GRANT EXECUTE ON "SA"."p_SaveEMPLOYEE" TO "some user or role here" ;


$$$

